import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import supabase from '../utils/supabase'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Game Consoles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Classic <a href="https://nextjs.org">Game Consoles</a>
        </h1>

        <p className={styles.description}>
          A collection of legendary game consoles{' '}
          <code className={styles.code}>by Monty</code>
        </p>

        <div className={styles.grid}>
          {props.logos.map(logo => {
            return (
              <Card 
                key={logo.id}
                name={logo.name}
                description={logo.description}
                url={logo.url}
              />
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const { data, error } = await supabase
    .from("logos")
    .select("*");

  if (error) {
    return {
      props: {
        error: error.message,
      }
    };
  }

  return {
    props: {
      logos: data
    }
  };
}
