name: Upload Figma Logos
on: [workflow_dispatch, repository_dispatch]
jobs:
  figma-image-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Upload Figma Logos to S3
        uses: ./.github/actions/figma-export
        env:
          FIGMA_TOKEN: ${{secrets.FIGMA_TOKEN}}
          FIGMA_FILE_URL: dvOacCbZKLqprvBNhnagg9
          AWS_S3_ACCESS_KEY: ${{secrets.AWS_S3_ACCESS_KEY}}
          AWS_S3_ACCESS_SECRET: ${{secrets.AWS_S3_ACCESS_SECRET}}
          AWS_S3_IMAGES_BUCKET_NAME: ${{secrets.AWS_S3_IMAGES_BUCKET_NAME}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
          
